apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  type: NodePort
  externalTrafficPolicy: Cluster
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
    nodePort:80
  - name: "443"
    port: 443
    targetPort: 8443
  selector:
    service: ambassador
