apiVersion: v1
kind: Service
metadata:
  name: ambassador
spec:
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - name: "80"
    port: 80
    targetPort: 8080
  - name: "443"
    port: 443
    targetPort: 8443
  selector:
    service: ambassador
