apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: keto
  name: keto
spec:
  containers:
  - env:
    - name: AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL
      value: ://:/oauth2/token
    - name: AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_ID
    - name: AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_SECRET
    - name: AUTHENTICATOR_OAUTH2_INTROSPECTION_TOKEN_URL
      value: ://:/oauth2/token
    - name: AUTHENTICATOR_OAUTH2_INTROSPECTION_URL
      value: ://:/oauth2/introspect
    - name: DATABASE_URL
      value: postgres://:@postgresd:5432/?sslmode=disable
    - name: LOG_LEVEL
    image: 'oryd/keto:'
    name: keto
    ports:
    - containerPort: 4466
    resources: {}
  restartPolicy: OnFailure
status: {}
