version: '3'

volumes:
  dcd-data-volume-mysql: {}
  dcd-data-volume-influxdb: {}
  volume-confluence: {}
  volume-confluence-postgres: {}

#  volume-mattermost-postgres: {}
#  volume-mattermost-app-config: {}
#  volume-mattermost-app-data: {}
#  volume-mattermost-app-logs: {}
#  volume-mattermost-app-plugins: {}

services:

  hydra-migrate:
    image: oryd/hydra:$HYDRA_VERSION
    container_name: hydra-migrate
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - HYDRA_SYSTEM_SECRET=$HYDRA_SYSTEM_SECRET
    command:
      migrate sql postgres://$AC_DB_USER:$AC_DB_PASSWORD@postgresd:5432/$AC_DB?sslmode=disable
    restart: on-failure

  keto-migrate:
    image: oryd/keto:$KETO_VERSION
    container_name: keto-migrate
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    command:
      migrate sql postgres://$AC_DB_USER:$AC_DB_PASSWORD@postgresd:5432/$AC_DB?sslmode=disable
    restart: on-failure

  oathkeeper-migrate:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    container_name: oathkeeper-migrate
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    command:
      migrate sql postgres://$AC_DB_USER:$AC_DB_PASSWORD@postgresd:5432/$AC_DB?sslmode=disable
    restart: on-failure


  postgresd:
    image: postgres:9.6
    container_name: postgres
    environment:
      - POSTGRES_USER=$AC_DB_USER
      - POSTGRES_PASSWORD=$AC_DB_PASSWORD
      - POSTGRES_DB=$AC_DB

  hydra:
    image: oryd/hydra:$HYDRA_VERSION
    container_name: hydra
    ports:
      - 4444:4444
      - 4445:4445
    depends_on:
      - hydra-migrate
    command:
#      serve all --dangerous-force-http
      serve all
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - SYSTEM_SECRET=$HYDRA_SYSTEM_SECRET
      - DATABASE_URL=postgres://$AC_DB_USER:$AC_DB_PASSWORD@postgresd:5432/$AC_DB?sslmode=disable
      - OAUTH2_CONSENT_URL=$PROTOCOL://$HOST:$PORT/auth/consent
      - OAUTH2_LOGIN_URL=$PROTOCOL://$HOST:$PORT/auth/signin
      - OAUTH2_LOGOUT_REDIRECT_URL=$PROTOCOL://$HOST:$PORT/ui
      - OAUTH2_ISSUER_URL=$PROTOCOL://$HOST:$PORT
      - OAUTH2_SHARE_ERROR_DEBUG=1
      - OAUTH2_ERROR_URL=$PROTOCOL://$HOST:$PORT/auth/error
      - ISSUER_URL=$PROTOCOL://$HOST:$PORT
      - HTTPS_ALLOW_TERMINATION_FROM=0.0.0.0/0
    restart: on-failure

#  oathkeeper-proxy:
#    image: oryd/oathkeeper:$OATHKEEPER_VERSION
#    container_name: oathkeeper-proxy
#    ports:
#      - $PORT:4455
#    depends_on:
#      - oathkeeper-api
#      - hydra
#      - keto
#    command:
#      serve proxy
#    environment:
#      - LOG_LEVEL=$LOG_LEVEL
#      - PORT=4455
#      - ISSUER_URL=$PROTOCOL://$HOST:$PORT/
#      - OATHKEEPER_API_URL=http://oathkeeper-api:4456
#      - CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM=ory-hydra
#      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID=resources:hydra:jwk:oathkeeper
#      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_ADMIN_URL=http://hydra:4445
#      - CREDENTIALS_ISSUER_ID_TOKEN_LIFESPAN=1h
#      - CREDENTIALS_ISSUER_ID_TOKEN_JWK_REFRESH_INTERVAL=30m
#      - CREDENTIALS_ISSUER_ID_TOKEN_ISSUER=http://$HOST:$PORT
#      - AUTHORIZER_KETO_WARDEN_KETO_URL=http://keto:4466
#
#      - AUTHENTICATOR_ANONYMOUS_USERNAME=anonymous
#
#      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_ID=$OATHKEEPER_CLIENT_ID
#      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_SECRET=$OATHKEEPER_CLIENT_SECRET
#      - AUTHENTICATOR_OAUTH2_INTROSPECTION_TOKEN_URL=http://hydra:4444/oauth2/token
#      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra:4445/oauth2/introspect
#      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=http://hydra:4444/oauth2/token
#
#      - AUTHENTICATOR_JWT_JWKS_URL=http://hydra/.well-known/jwks.json
#    restart: on-failure



  ambassador:
    image: quay.io/datawire/ambassador:0.38.0
    ports:
    - 80:80
    - 443:443
    volumes:
    - ./config:/ambassador/ambassador-config
    - ./etc/ssl/certs:/etc/certs

  oathkeeper-api:
    image: oryd/oathkeeper:$OATHKEEPER_VERSION
    container_name: oathkeeper-api
    ports:
      - 4456:4456
    depends_on:
      - hydra-migrate
    command:
      serve api
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - PORT=4456
      - DATABASE_URL=postgres://$AC_DB_USER:$AC_DB_PASSWORD@postgresd:5432/$AC_DB?sslmode=disable
      - ISSUER_URL=http://$PORT:$HOST
      - AUTHORIZER_KETO_WARDEN_KETO_URL=http://keto:4466
      - CREDENTIALS_ISSUER_ID_TOKEN_ALGORITHM=ory-hydra
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_JWK_SET_ID=resources:hydra:jwk:oathkeeper
      - CREDENTIALS_ISSUER_ID_TOKEN_HYDRA_ADMIN_URL=http://hydra:4445
      - CREDENTIALS_ISSUER_ID_TOKEN_LIFESPAN=1h
      - CREDENTIALS_ISSUER_ID_TOKEN_ISSUER=http://oathkeeper-api:4456
      - CREDENTIALS_ISSUER_ID_TOKEN_JWK_REFRESH_INTERVAL=30m
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra:4445/oauth2/introspect
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=http://hydra:4444/oauth2/token
    restart: on-failure

  keto:
    image: oryd/keto:$KETO_VERSION
    container_name: keto
    ports:
      - 4466:4466
    depends_on:
      - hydra
      - keto-migrate
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - DATABASE_URL=postgres://$AC_DB_USER:$AC_DB_PASSWORD@postgresd:5432/$AC_DB?sslmode=disable
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_ID=$KETO_CLIENT_ID
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_SECRET=$KETO_CLIENT_SECRET
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_TOKEN_URL=http://hydra:4444/oauth2/token
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=http://hydra:4445/oauth2/introspect
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=http://hydra:4444/oauth2/token
    restart: on-failure

  configurator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HYDRA_VERSION=$HYDRA_VERSION
        - KETO_VERSION=$KETO_VERSION
        - OATHKEEPER_VERSION=$OATHKEEPER_VERSION
    container_name: configurator
    depends_on:
      - hydra
      - keto
      - oathkeeper-api
    volumes:
      - ./scripts:/scripts
    environment:
      # All of these URLs MUST NOT end with a trailing slash. This is very important!
      - HYDRA_URL=http://hydra:4444
      - HYDRA_ADMIN_URL=http://hydra:4445
      - KETO_URL=http://keto:4466
      - OATHKEEPER_API_URL=http://oathkeeper-api:4456
      - OATHKEEPER_PROXY_URL=$PROTOCOL://$HOST:$PORT

      # This sets the prefix for all resource, action, and subject names.
      # Be aware that this prefix is automatically applied to all OAuth2 Clients as well.
      - "HYDRA_SUBJECT_PREFIX=subjects:hydra:"
      - "HYDRA_RESOURCE_PREFIX=resources:hydra:"
      - "HYDRA_ACTION_PREFIX=actions:hydra:"
      - "OATHKEEPER_RESOURCE_PREFIX=resources:oathkeeper:"
      - "OATHKEEPER_ACTION_PREFIX=actions:oathkeeper:"
      - "KETO_RESOURCE_PREFIX=resources:keto:"
      - "KETO_ACTION_PREFIX=actions:keto:"

      - OATHKEEPER_HYDRA_JWK_SET_ID=jwk:oathkeeper
      - OATHKEEPER_HYDRA_CLIENT_ID=$OATHKEEPER_CLIENT_ID
      - OATHKEEPER_HYDRA_CLIENT_SECRET=$OATHKEEPER_CLIENT_SECRET
      - KETO_HYDRA_CLIENT_ID=$KETO_CLIENT_ID
      - KETO_HYDRA_CLIENT_SECRET=$KETO_CLIENT_SECRET
    restart: on-failure

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=$HOST
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - "KAFKA_CREATE_TOPICS=things:1:1:compact,persons:1:1:compact,properties:1:1:compact,values:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  # == == == == == Stores == == == == ==

  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - dcd-data-volume-influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083
    environment:
      - INFLUXDB_DB=$INFLUXDB_DB
      - INFLUXDB_ADMIN_ENABLED=true

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_SYSTEM_SECRET
    volumes:
      - dcd-data-volume-mysql:/var/lib/mysql
      - ./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  # == == == == == Services == == == == ==

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
#    ports:
#      - 3000:3000
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource
      - GF_SERVER_ROOT_URL=$PROTOCOL://$HOST:$PORT/grafana
      - GF_SECURITY_ADMIN_PASSWORD=$GRAFANA_ADMIN_PASS
#      - GF_SERVER_PROTOCOL=$PROTOCOL
#      - GF_SERVER_CERT_FILE=$SSL_KEY_PATH
#      - GF_SERVER_CERT_KEY=$SSL_CERT_PATH

  # == == == == == Data-Centric Hub == == == == ==


  dcd-auth:
#    image: datacentricdesign/dcd-auth:
    build:
      context: ../dcd-auth
      dockerfile: Dockerfile
    container_name: auth
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - HTTPS=true

  dcd-api-http:
#    image: datacentricdesign/dcd-api-http:
    container_name: dcd-api-http
    build:
      context: ../dcd-api-http
      dockerfile: Dockerfile
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - PORT=4478
      - CRYPTO_KEY=$CRYPTO_KEY
      - MODEL_HOST=$HOST
      - KAFKA=true
      - HTTPS=true
      - KAFKA_HOST=$HOST
      - KAFKA_PORT=$KAFKA_PORT
      - API_URL=$PROTOCOL://$HOST:$PORT/api
      - KETO_URL=http://keto:4466
      - HYDRA_ADMIN_URL=http://hydra:4445
      - HYDRA_URL=http://hydra:4444
      - OATHKEEPER_KEY_URL=http://oathkeeper-api:4456/.well-known/jwks.json
      - OAUTH2_TOKEN_URL=http://hydra:4444/oauth2/token
      - OAUTH2_CLIENT_ID=$API_OAUTH2_CLIENT_ID
      - OAUTH2_CLIENT_SECRET=$API_OAUTH2_CLIENT_SECRET
      - OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect

  dcd-api-mqtt:
#    image: datacentricdesign/dcd-api-mqtt:
    build:
      context: ../dcd-api-mqtt
      dockerfile: Dockerfile
    container_name: dcd-api-mqtt
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - HTTPS=true


  dcd-store-influxdb:
#    image: datacentricdesign/dcd-store-influxdb:
    build:
      context: ../dcd-store-influxdb
      dockerfile: Dockerfile
    container_name: dcd-store-influxdb

  dcd-web-ui:
#    image: datacentricdesign/dcd-web-ui:
    build:
      context: ../dcd-web-ui
      dockerfile: Dockerfile
    container_name: dcd-web-ui
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - HTTPS=true


#  dcd-website:
#    image: datacentricdesign/dcd-website:
#    container_name: dcd-website

#  dcd-proxy:
#    image: datacentricdesign/dcd-proxy:
#    container_name: dcd-proxy
#    ports:
#      - 80:80
#    environment:
#      - PORT=80
#      - SSL=false
#      - SSL_KEY_PATH=$SSL_KEY_PATH
#      - SSL_CERT_PATH=$SSL_CERT_PATH
#      - SSL_REDIRECT_PORT=$SSL_REDIRECT_PORT