version: '3'

services:

  hydra-migrate:
    image: oryd/hydra:$HYDRA_VERSION
    container_name: hydra-migrate
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - HYDRA_SYSTEM_SECRET=$HYDRA_SYSTEM_SECRET
    command:
      migrate sql postgres://$AC_DB_USER:$AC_DB_PASSWORD@postgresd:5432/$AC_DB?sslmode=disable --yes
    restart: on-failure

  keto-migrate:
    image: oryd/keto:$KETO_VERSION
    container_name: keto-migrate
    environment:
      - LOG_LEVEL=$LOG_LEVEL
    command:
      migrate sql postgres://$AC_DB_USER:$AC_DB_PASSWORD@postgresd:5432/$AC_DB?sslmode=disable --yes
    restart: on-failure

  hydra:
    image: oryd/hydra:$HYDRA_VERSION
    container_name: hydra
    ports:
      - 4444:4444
      - 4445:4445
    depends_on:
      - hydra-migrate
    command:
      serve all
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - SECRETS_SYSTEM=$HYDRA_SYSTEM_SECRET
      - DSN=postgres://$AC_DB_USER:$AC_DB_PASSWORD@postgresd:5432/$AC_DB?sslmode=disable
      - OAUTH2_CONSENT_URL=$PROTOCOL://$HOST:$PORT/auth/consent
      - URLS_LOGIN=$PROTOCOL://$HOST:$PORT/auth/signin
      - OAUTH2_LOGOUT_REDIRECT_URL=$PROTOCOL://$HOST:$PORT/
      - OAUTH2_EXPOSE_INTERNAL_ERRORS=1
      - OAUTH2_ERROR_URL=$PROTOCOL://$HOST:$PORT/auth/error
      - URLS_SELF_ISSUER=$PROTOCOL://$HOST:$PORT
      - TTL_AUTH_CODE=24h
      - TTL_ID_TOKEN=24h
      - TTL_ACCESS_TOKEN=24h
      - TTL_REFRESH_TOKEN=720h
      - TTL_LOGIN_CONSENT_REQUEST=15m
      - ISSUER_URL=$PROTOCOL://$HOST:$PORT
      - SERVE_TLS_ALLOW_TERMINATION_FROM=172.19.0.22/24
      - CORS_ALLOWED_ORIGINS=http://localhost:4200
    volumes:
      - ./certs:/etc/certs
      - ./config/hydra/.hydra:/.hydra
    restart: on-failure

  ambassador:
    image: quay.io/datawire/ambassador:0.76.0
    container_name: ambassador
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./config/ambassador:/ambassador/ambassador-config
      - ./certs:/etc/certs
    environment:
      # don't try to watch Kubernetes for configuration changes
      - AMBASSADOR_NO_KUBEWATCH=no_kubewatch
      - AMBASSADOR_NO_SECRETS=True

  keto:
    image: oryd/keto:$KETO_VERSION
    container_name: keto
    ports:
      - 4466:4466
    depends_on:
      - hydra
      - keto-migrate
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - DATABASE_URL=postgres://$AC_DB_USER:$AC_DB_PASSWORD@postgresd:5432/$AC_DB?sslmode=disable
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_ID=$KETO_CLIENT_ID
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_CLIENT_SECRET=$KETO_CLIENT_SECRET
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_TOKEN_URL=$PROTOCOL://$HOST:$PORT/oauth2/token
      - AUTHENTICATOR_OAUTH2_INTROSPECTION_URL=$PROTOCOL://$HOST:$PORT/oauth2/introspect
      - AUTHENTICATOR_OAUTH2_CLIENT_CREDENTIALS_TOKEN_URL=$PROTOCOL://$HOST:$PORT/oauth2/token
    restart: on-failure

  configurator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - HYDRA_VERSION=$HYDRA_VERSION
        - KETO_VERSION=$KETO_VERSION
    container_name: configurator
    depends_on:
      - hydra
      - keto
    volumes:
      - ./scripts:/scripts
    environment:
      # All of these URLs MUST NOT end with a trailing slash. This is very important!
      - HYDRA_URL=http://hydra:4444
      - HYDRA_ADMIN_URL=http://hydra:4445
      - KETO_URL=http://keto:4466
#      - OATHKEEPER_API_URL=http://oathkeeper-api:4456
#      - OATHKEEPER_PROXY_URL=$PROTOCOL://$HOST:$PORT

      # This sets the prefix for all resource, action, and subject names.
      # Be aware that this prefix is automatically applied to all OAuth2 Clients as well.
      - "HYDRA_SUBJECT_PREFIX=subjects:hydra:"
      - "HYDRA_RESOURCE_PREFIX=resources:hydra:"
      - "HYDRA_ACTION_PREFIX=actions:hydra:"
      - "OATHKEEPER_RESOURCE_PREFIX=resources:oathkeeper:"
      - "OATHKEEPER_ACTION_PREFIX=actions:oathkeeper:"
      - "KETO_RESOURCE_PREFIX=resources:keto:"
      - "KETO_ACTION_PREFIX=actions:keto:"

#      - OATHKEEPER_HYDRA_JWK_SET_ID=jwk:oathkeeper
#      - OATHKEEPER_HYDRA_CLIENT_ID=$OATHKEEPER_CLIENT_ID
#      - OATHKEEPER_HYDRA_CLIENT_SECRET=$OATHKEEPER_CLIENT_SECRET
      - KETO_CLIENT_ID=$KETO_CLIENT_ID
      - KETO_CLIENT_SECRET=$KETO_CLIENT_SECRET
      - API_HTTP_CLIENT_ID=$API_HTTP_CLIENT_ID
      - API_HTTP_CLIENT_SECRET=$API_HTTP_CLIENT_SECRET
      - API_MQTT_CLIENT_ID=$API_MQTT_CLIENT_ID
      - API_MQTT_CLIENT_SECRET=$API_MQTT_CLIENT_SECRET
      - APP_IDENTITY_PROVIDER_CLIENT_ID=$APP_IDENTITY_PROVIDER_CLIENT_ID
      - APP_IDENTITY_PROVIDER_CLIENT_SECRET=$APP_IDENTITY_PROVIDER_CLIENT_SECRET
      - APP_SUBJECT_CLIENT_ID=$APP_SUBJECT_CLIENT_ID
      - APP_SUBJECT_CLIENT_SECRET=$APP_SUBJECT_CLIENT_SECRET
      - APP_DESIGNER_CLIENT_ID=$APP_DESIGNER_CLIENT_ID
      - APP_DESIGNER_CLIENT_SECRET=$APP_DESIGNER_CLIENT_SECRET
      - APP_MOBILE_CLIENT_ID=$APP_MOBILE_CLIENT_ID
      - PORT=$PORT
      - PROTOCOL=$PROTOCOL
      - HOST=$HOST
    restart: on-failure

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=$HOST
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - "KAFKA_CREATE_TOPICS=things:1:1:compact,persons:1:1:compact,properties:1:1:compact,values:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  # == == == == == Stores == == == == ==

  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - /data/influxdb:/var/lib/influxdb
    ports:
      - 8086:8086
      - 8083:8083
    environment:
      - INFLUXDB_DB=$INFLUXDB_DB
      - INFLUXDB_ADMIN_ENABLED=true

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_SYSTEM_SECRET
    volumes:
      - /data/mysql:/var/lib/mysql
      - ./config/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306

  postgresd:
    image: postgres:9.6
    container_name: postgres
    environment:
      - POSTGRES_USER=$AC_DB_USER
      - POSTGRES_PASSWORD=$AC_DB_PASSWORD
      - POSTGRES_DB=$AC_DB
    volumes:
      - /data/postgresql:/var/lib/postgresql

  # == == == == == Logging == == == == ==

  logspout:
    image: bekt/logspout-logstash
    container_name: logspout
    restart: on-failure
    environment:
      ROUTE_URIS: logstash://logstash:5000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  logstash:
    image: logstash:7.2.0
    container_name: logstash
    command: bin/logstash -f /opt/logstash/logstash.conf
    volumes:
      - ./config/logs/logstash.conf:/opt/logstash/logstash.conf
      - /data/logs:/var/log/logstash

  # == == == == == Data-Centric Hub - APIs == == == == ==

  dcd-api-http:
    image: datacentricdesign/dcd-api-http:$DCD_API_HTTP_VERSION
    container_name: dcd-api-http
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - PORT=4478
      - CRYPTO_KEY=$CRYPTO_KEY
      - MODEL_HOST=$HOST
      - KAFKA=true
      - HTTPS=true
      - KAFKA_HOST=kafka
      - KAFKA_PORT=$KAFKA_PORT
      - API_URL=$PROTOCOL://$HOST:$PORT/api
      - KETO_URL=http://keto:4466
      - HYDRA_ADMIN_URL=http://hydra:4445
      - HYDRA_URL=$PROTOCOL://$HOST:$PORT
      - OATHKEEPER_KEY_URL=http://oathkeeper-api:4456/.well-known/jwks.json
      - OAUTH2_TOKEN_URL=http://hydra:4444/oauth2/token
      - OAUTH2_REVOKE_URL=http://hydra:4444/oauth2/revoke
      - OAUTH2_CLIENT_ID=$API_HTTP_CLIENT_ID
      - OAUTH2_CLIENT_SECRET=$API_HTTP_CLIENT_SECRET
      - OAUTH2_INTROSPECT_URL=http://hydra:4445/oauth2/introspect
    volumes:
      - /data/files:/usr/src/app/files

  dcd-api-mqtt:
    image: datacentricdesign/dcd-api-mqtt:$DCD_API_MQTT_VERSION
    container_name: dcd-api-mqtt
    ports:
      - 8883:8883
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - HTTPS=true
      - MQTT_HOST=0.0.0.0
      - MQTT_PORT=8883
      - CRYPTO_KEY=$CRYPTO_KEY
      - KAFKA=true
      - KAFKA_HOST=kafka
      - KAFKA_PORT=$KAFKA_PORT
      - OAUTH2_CLIENT_ID=$API_MQTT_CLIENT_ID
      - OAUTH2_CLIENT_SECRET=$API_MQTT_CLIENT_SECRET
      - MODEL_HOST=$HOST
      - API_URL=$PROTOCOL://$HOST:$PORT/api
      - KETO_URL=http://keto:4466
      - HYDRA_ADMIN_URL=http://hydra:4445
      - OAUTH2_TOKEN_URL=http://hydra:4444/oauth2/token
      - OAUTH2_REVOKE_URL=http://hydra:4444/oauth2/revoke
      - MQTT_CLIENT_USER=$API_MQTT_CLIENT_ID
      - MQTT_CLIENT_PASS=$API_MQTT_CLIENT_SECRET
    volumes:
      - ./certs:/etc/certs

  # == == == == == Data-Centric Hub - Stores == == == == ==

  dcd-store-influxdb:
    image: datacentricdesign/dcd-store-influxdb:$DCD_STORE_INFLUXDB_VERSION
    container_name: dcd-store-influxdb
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - INFLUXDB_HOST=influxdb
      - INFLUXDB_NAME=dcdhub
      - HTTPS=true
      - CRYPTO_KEY=$CRYPTO_KEY
      - KAFKA=true
      - KAFKA_HOST=kafka
      - KAFKA_PORT=$KAFKA_PORT

  # == == == == == Data-Centric Hub - Apps == == == == ==

  dcd-app-identity-provider:
    image: datacentricdesign/dcd-app-identity-provider:$DCD_APP_IDENTITY_PROVIDER_VERSION
    container_name: dcd-app-identity-provider
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - HTTPS=true
      - PORT=8888
      - CRYPTO_KEY=$CRYPTO_KEY
      - API_URL=http://dcd-api-http:4478/api
      - KETO_URL=$PROTOCOL://$HOST:$PORT
      - HYDRA_ADMIN_URL=http://hydra:4445
      - OAUTH2_TOKEN_URL=http://hydra:4444/oauth2/token
      - OAUTH2_REVOKE_URL=http://hydra:4444/oauth2/revoke
      - OAUTH2_CLIENT_ID=$APP_IDENTITY_PROVIDER_CLIENT_ID
      - OAUTH2_CLIENT_SECRET=$APP_IDENTITY_PROVIDER_CLIENT_SECRET

  dcd-app-subject:
    image: datacentricdesign/dcd-app-subject:$DCD_APP_SUBJECT_VERSION
    container_name: dcd-app-subject
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - HTTPS=true
      - PORT=8080
      - BASE_URL=/subject
      - SERVER_URL=$PROTOCOL://$HOST:$PORT
      - NODE_TLS_REJECT_UNAUTHORIZED=0
      - OAUTH2_AUTH_URL=$PROTOCOL://$HOST:$PORT/oauth2/auth
      - OAUTH2_TOKEN_URL=$PROTOCOL://$HOST:$PORT/oauth2/token
      - OAUTH2_REVOKE_URL=$PROTOCOL://$HOST:$PORT/oauth2/revoke
      - OAUTH2_CLIENT_ID=$APP_SUBJECT_CLIENT_ID
      - OAUTH2_CLIENT_SECRET=$APP_SUBJECT_CLIENT_SECRET
      - OAUTH2_PROFILE=$PROTOCOL://$HOST:$PORT/userinfo
      - OAUTH2_REDIRECT_URL=$PROTOCOL://$HOST:$PORT/subject/auth/callback
      - API_URL=$PROTOCOL://$HOST:$PORT/api
      - MAPS_KEY=$MAPS_KEY

  dcd-app-designer:
    image: datacentricdesign/dcd-app-designer:$DCD_APP_DESIGNER_VERSION
    container_name: dcd-app-designer
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - HTTPS=true
      - PORT=8080
      - BASE_URL=/designer
      - SERVER_URL=$PROTOCOL://$HOST:$PORT
      - OAUTH2_AUTH_URL=$PROTOCOL://$HOST:$PORT/oauth2/auth
      - OAUTH2_TOKEN_URL=http://hydra:4444/oauth2/token
      - OAUTH2_REVOKE_URL=http://hydra:4444/oauth2/revoke
      - OAUTH2_CLIENT_ID=$APP_DESIGNER_CLIENT_ID
      - OAUTH2_CLIENT_SECRET=$APP_DESIGNER_CLIENT_SECRET
      - OAUTH2_PROFILE=$PROTOCOL://$HOST:$PORT/userinfo
      - OAUTH2_REDIRECT_URL=$PROTOCOL://$HOST:$PORT/designer/auth/callback
      - API_URL=$PROTOCOL://$HOST:$PORT/api

  dcd-website:
    image: datacentricdesign/dcd-website:$DCD_WEBSITE_VERSION
    container_name: dcd-website

  # == == == == == Data-Centric Hub - Processors == == == == ==

  dcd-processor:
    image: datacentricdesign/dcd-processor:$DCD_PROCESSOR_VERSION
    container_name: dcd-processor
    environment:
      - LOG_LEVEL=$LOG_LEVEL
      - HTTPS=true
      - CRYPTO_KEY=$CRYPTO_KEY
      - KAFKA=true
      - KAFKA_HOST=kafka
      - KAFKA_PORT=$KAFKA_PORT
      - CHECK_ACTIVITY_COUNT=60000
      - AUTH_ENABLED=false
