apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: logstash
    spec:
      containers:
      - args:
        - bin/logstash
        - -f
        - /opt/logstash/logstash.conf
        image: logstash:7.2.0
        name: logstash
        resources: {}
        volumeMounts:
        - mountPath: /opt/logstash/logstash.conf
          name: logstash-claim0
        - mountPath: /var/log/logstash
          name: logstash-claim1
      restartPolicy: Always
      volumes:
      - name: logstash-claim0
        persistentVolumeClaim:
          claimName: logstash-claim0
      - name: logstash-claim1
        persistentVolumeClaim:
          claimName: logstash-claim1
status: {}
